name: Prepare QCW Podman (from revision)
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      podman_version:
        description: Podman version"
        value: ${{ jobs.build.outputs.podman_version }}
env:
  PODMAN_GITURL: https://github.com/containers/podman.git
  PODMAN_SHA: 3c4cf521428ce11906976ddd08a5a6e8626cd50e # v5.5.0-rc2
  PODMAN_VERSION: 5.5.0-rc2
  PODMAN_REVISION_KIND: prod # prod|dev
jobs:
  build:
    runs-on: windows-2022
    outputs:
      podman_version: ${{ steps.make_versions.outputs.podman }}
    steps:
      - name: "🏗️ Install msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            make git unzip base-devel man-db mingw-w64-ucrt-x86_64-toolchain zip mingw-w64-ucrt-x86_64-go
      - name: "📝 Configure checkout"
        run: git config --global core.autocrlf input
      - name: "📝 Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: "📝 Fetch sources"
        shell: msys2 {0}
        run: |
          mkdir podman-release
          cd podman-release
          git init
          git remote add origin $PODMAN_GITURL
          git fetch --depth 1 origin $PODMAN_SHA
          git checkout FETCH_HEAD
      - name: "⚗️ Prepare Test Podman"
        working-directory: podman-release
        shell: msys2 {0}
        run: |
          HELPER_BINARIES_DIR=`cygpath -w "$(pwd)/bin/windows"` make clean podman-remote win-gvproxy
      - name: "🧪 Test Podman"
        working-directory: podman-release
        shell: pwsh
        env:
          CONTAINERS_MACHINE_PROVIDER: hyperv
          MACHINE_TEST_TIMEOUT: 360
        run: |
          ./winmake localmachine "cp_test.go"
