name: Prepare QCW QEMU (from TarBall sources)

on: workflow_dispatch

env:
  QEMU_VERSION: 8.1.0

jobs:

  build:
    runs-on: windows-latest

    steps:

    - name: '🏗️ Install msys2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          make
          git
          unzip
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          python
          ninja
          mingw-w64-ucrt-x86_64-glib2
          mingw-w64-ucrt-x86_64-pixman
          python-setuptools
          mingw-w64-ucrt-x86_64-gtk3
          mingw-w64-ucrt-x86_64-SDL2
          mingw-w64-ucrt-x86_64-libslirp
          mingw-w64-ucrt-x86_64-SDL2_image
          mingw-w64-ucrt-x86_64-curl-gnutls
          mingw-w64-ucrt-x86_64-gnutls
          mingw-w64-ucrt-x86_64-virglrenderer
          mingw-w64-ucrt-x86_64-libssh
          mingw-w64-ucrt-x86_64-libssh2
          mingw-w64-ucrt-x86_64-meson
          mingw-w64-ucrt-x86_64-nsis

    - name: '🏗️ Install tools'
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install 7zip.install

    - name: '📝 Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: '🔗 Link tools'
      shell: msys2 {0}
      run: |
        mkdir -p /usr/local/bin
        ln -sf "/c/Program Files/7-Zip/7z.exe" "/usr/local/bin/7z.exe"

    - name: '📝 Fetch sources'
      shell: msys2 {0}
      run: |
        wget -q "https://download.qemu.org/qemu-$QEMU_VERSION.tar.xz"
        wget -q "https://download.qemu.org/qemu-$QEMU_VERSION.tar.xz.sig"
        gpg --keyserver keys.openpgp.org --recv-key CEACC9E15534EBABB82D3FA03353C9CEF108B584
        gpg "qemu-$QEMU_VERSION.tar.xz.sig"
        7z x "qemu-$QEMU_VERSION.tar.xz"
        7z x "qemu-$QEMU_VERSION.tar"
        mv "qemu-$QEMU_VERSION" qemu-release
        cd qemu-release
        patch -p 1 < ../patches/qemu/0001-9pfs-Add-9pfs-support-for-Windows-host.patch
        patch -p 1 < ../patches/qemu/0002-WHPX-Add-support-for-device-backed-memory-regions.patch
        patch -p 1 < ../patches/qemu/0003-Windows-installer-keep-dependency-cache.patch

    - name: '🛠️ Build QEMU'
      working-directory: qemu-release
      shell: msys2 {0}
      run: |
        ./configure --enable-gtk --enable-sdl --disable-debug-info
        make
        make installer

    - name: '📦 Pack QEMU'
      shell: msys2 {0}
      run: |
        mkdir -p qcw
        cp qemu-release/build/qemu-setup-*.exe qcw/
        cd qcw
        find . -type f \( ! -iname "*.checksums" \) -exec sha256sum -b {} \; > sha.checksums
        find . -type f \( ! -iname "*.checksums" \) -exec sha512sum -b {} \; >> sha.checksums
        cat sha.checksums

    - name: '🚀 Upload artifact'
      uses: actions/upload-artifact@v3
      with:
        name: qcw-qemu
        path: qcw
