name: Prepare QCW Docker (from revision)
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      cli_version:
        description: "Docker CLI version"
        value: ${{ jobs.build.outputs.cli_version }}
      compose_version:
        description: "Docker Compose version"
        value: ${{ jobs.build.outputs.compose_version }}
env:
  CLI_GITURL: https://github.com/docker/cli.git
  CLI_SHA: a7dcaa6fdb6ed04aacbfdc76357fdae01605609e # v29.7.2
  CLI_VERSION: 29.7.2
  COMPOSE_GITURL: https://github.com/docker/compose.git
  COMPOSE_SHA: 870908cc8f07f5e90acdf5d34dd1b96a4fe51d16 # v5.5.0
  COMPOSE_VERSION: 5.5.0
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cli_version: ${{ steps.make_versions.outputs.cli }}
      compose_version: ${{ steps.make_versions.outputs.compose }}
    steps:
      - name: 🏗️ Install Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: "📝 Configure checkout"
        run: git config --global core.autocrlf input
      - name: "📝 Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: "📝 Fetch sources CLI"
        run: |
          mkdir docker-cli-release
          cd docker-cli-release
          git init
          git remote add origin $CLI_GITURL
          git fetch --depth 1 origin $CLI_SHA
          git checkout FETCH_HEAD
      - name: "📝 Fetch sources Compose"
        run: |
          mkdir docker-compose-release
          cd docker-compose-release
          git init
          git remote add origin $COMPOSE_GITURL
          git fetch --depth 1 origin $COMPOSE_SHA
          git checkout FETCH_HEAD
      - name: "🛠️ Build Docker CLI"
        working-directory: docker-cli-release
        run: |
          docker buildx bake --set binary.platform=windows/amd64
      - name: "🛠️ Build Docker Compose"
        working-directory: docker-compose-release
        run: |
          docker buildx bake --set binary.platform=windows/amd64
      - name: "📦 Pack Docker"
        run: |
          mkdir -p qcw
          cp docker-cli-release/build/docker-windows-amd64.exe qcw/docker.exe
          cp docker-compose-release/bin/build/docker-compose.exe qcw/docker-compose.exe
          cd qcw
          find . -type f \( ! -iname "*.checksums" \) -exec sha256sum -b {} \; > sha.checksums
          find . -type f \( ! -iname "*.checksums" \) -exec sha512sum -b {} \; >> sha.checksums
          cat sha.checksums
      - id: make_versions
        name: "📌 Export versions"
        run: |
          echo "cli=$CLI_VERSION" >> "$GITHUB_OUTPUT"
          echo "compose=$COMPOSE_VERSION" >> "$GITHUB_OUTPUT"
      - name: "🚀 Upload artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: qcw-docker
          path: qcw
